version: '3.8'

services:
   fairseller-api:
     build: ./
     environment:
       - PG_URL=${PG_URL_DOCKER}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_DATABASE=${DB_DATABASE}
       - DB_PORT=${DB_PORT}
       - HTTP_PORT=${HTTP_PORT}
       - SOCKET_PORT=${SOCKET_PORT}
       - REDIS_PORT=${REDIS_PORT}
       - REDIS_HOST=${REDIS_HOST_DOCKER}
       - DB_HOST=${DB_HOST_DOCKER}
     volumes:
       - ./uploads/:/uploads
       - ./logs/:/logs
     ports:
      - ${HTTP_PORT}:3000
      - ${SOCKET_PORT}:80
     env_file:
       - .env


   postgres:
     image: postgres:13.4
     volumes:
       - ./database/:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=${DB_USERNAME}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_DATABASE}
     ports:
       - ${DB_PORT}:5432
     env_file:
       - .env

   redis:
     image: redis:6.2.6
     volumes:
       - ./redis:/data
     ports:
       - ${REDIS_PORT}:6379
     env_file:
       - .env