app:
  name: 'fairseller-backend'
  version: '1.0.0'

http:
  port: '3000'

logger:
  log_level: 'debug'
  rollbar_env: 'fairseller-backend'

postgres:
  pool_max: 2

database:
  user: 'fairseller'
  password: 'fairseller'
  name: 'fairseller'
  port: '5432'

redis: 
  host: 'localhost'
  port: '6379'