basePath: /v1
definitions:
  v1.SignUpRequestDto:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Api for fairseller APP
  title: Fairseller API
  version: "1.0"
paths:
  /auth/sign-up-request:
    post:
      consumes:
      - application/json
      description: Sign up first step with send code to mobile
      parameters:
      - description: Phone for getting code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.SignUpRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Sign up
      tags:
      - Auth
swagger: "2.0"
